# Generated by Django 3.2 on 2021-04-11 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('switchmart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='browse',
            name='details',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
