# Generated by Django 3.2 on 2021-04-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchmart', '0002_browse_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browse',
            name='price',
            field=models.IntegerField(),
        ),
    ]
