# Generated by Django 3.2 on 2021-04-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchmart', '0004_cart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
