# Generated by Django 3.2 on 2021-04-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchmart', '0005_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='category',
            field=models.TextField(default='haha'),
            preserve_default=False,
        ),
    ]
