# Generated by Django 3.2 on 2021-04-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchmart', '0006_cart_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='category',
            field=models.TextField(),
        ),
    ]
