# Generated by Django 3.2 on 2021-04-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchmart', '0007_alter_filters_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(),
        ),
    ]
